name: Manual Workflow

on:
  workflow_dispatch:  # déclenchement manuel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo test
        run: echo "Workflow manuel lancé"
